### ISSUE TITLE
Use Defaults

### ISSUE THREAD

**Issue by oleersoy** [Hypercubed/docpad-plugin-geturl#2]
Reference:
http://publib.boulder.ibm.com/infocenter/cicsts/v3r1/index.jsp?topic=%2Fcom.ibm.cics.ts31.doc%2Fdfhtl%2Ftopics%2Fdfhtl_uricomp.htm

DEFAULTS

```
# ...
  templateData:
        site:
            host: localhost
            scheme: http
            port: 9778
# ...
```

The developer would not have to configure the above.  They should be retrieved from docpad as defaults.

If the developer want different settings, then just override the above.
